#!/usr/bin/env python3
"""
Snapshot M12 PS3 roster + franchise templates from RPCS3's dev_hdd0 into
out/templates/. The PS3 pipeline can't use the PS2 .max/.psu templates;
it needs a fresh M12 PS3 save (bare BE TDB, no PFD encryption) that the
user generated by booting BLUS30770 in RPCS3.

Procedure for the user:
  1. Install Madden NFL 12 (BLUS30770) in RPCS3.
  2. Boot the game. Main menu -> Roster -> save the default roster.
  3. Main menu -> Franchise Mode -> Start New Franchise -> pick any team
     -> click through to the franchise main screen -> save.
  4. Close RPCS3 cleanly.
  5. Run this script. It picks the most-recent BLUS30770-ROSTER-* and
     BLUS30770-FRANCHISE-* save folders and copies their USR-DATA into
     out/templates/madden-nfl-12-ps3-{roster,franchise}-template.bin.

The templates are big-endian TDB v8. MaddenTdb auto-detects the endian
from the file contents (looks at the table-count field), so the C#
pipeline doesn't need any compile-time configuration to handle them.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

DEFAULT_DEV_HDD0 = Path("/mnt/c/Emulators/RPCS3/dev_hdd0/home/00000001/savedata")
REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = REPO_ROOT / "out" / "templates"

GAME_ID = "BLUS30770"  # Madden NFL 12 PS3 (US)


def latest_save(savedata_dir: Path, kind: str) -> Path | None:
    """Find the most-recently-modified save folder matching {GAME_ID}-{KIND}-*."""
    candidates = sorted(
        savedata_dir.glob(f"{GAME_ID}-{kind}-*"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def fetch_one(savedata_dir: Path, kind: str, out_name: str) -> bool:
    """kind: ROSTER, FRANCHISE, ... | out_name: madden-nfl-12-ps3-roster-template.bin"""
    save_dir = latest_save(savedata_dir, kind)
    if save_dir is None:
        print(f"  no {GAME_ID}-{kind}-* save found under {savedata_dir}", file=sys.stderr)
        return False
    src = save_dir / "USR-DATA"
    if not src.exists():
        print(f"  {save_dir} has no USR-DATA inside", file=sys.stderr)
        return False
    TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
    dst = TEMPLATES_DIR / out_name
    shutil.copyfile(src, dst)
    size = dst.stat().st_size
    print(f"  copied {src} -> {dst} ({size:,} bytes)")
    return True


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--savedata-dir", type=Path, default=DEFAULT_DEV_HDD0,
                   help=f"RPCS3 savedata root (default {DEFAULT_DEV_HDD0})")
    args = p.parse_args()

    if not args.savedata_dir.is_dir():
        print(f"savedata-dir does not exist: {args.savedata_dir}", file=sys.stderr)
        return 2

    print(f"Snapshotting from {args.savedata_dir} ...")
    ok = True
    ok &= fetch_one(args.savedata_dir, "ROSTER",    "madden-nfl-12-ps3-roster-template.bin")
    ok &= fetch_one(args.savedata_dir, "FRANCHISE", "madden-nfl-12-ps3-franchise-template.bin")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
